source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'ImagePickerDemo' do
	use_frameworks!

	pod 'ImagePicker', path: '../../'
	pod 'Lightbox', :git => 'https://github.com/sedwo/Lightbox.git'
	pod 'Hue'
  pod 'CocoaLumberjack/Swift'
end